import eslint from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

import { plugin } from './tools/eslint-plugin/index.js';

export default tseslint.config(
  {
    ignores: [
      '.ci-tools/**',
      'build/**',
      'coverage/**',
      'dist/**',
      'node_modules/**',
      'vendor/**',
      // Emscripten glue, generated by scripts/build-pico-module.sh.
      'src/pico.mjs',
      'src/pico-multi.mjs',
      // Local build output of the demo, the browser gate and the WebGPU spikes.
      'spikes/**/dist/**',
      'spikes/webgpu/picovoxel-dist/**',
      'test/browser/gate-dist/**',
      'test/browser/vendor/**',
      // The maintainer's working files stay out of lint (and format, see
      // .oxfmtrc.json) so an edit in progress cannot fail a pull request. tsc
      // still type-checks them, and vitest still runs the test file.
      'demo/main.ts',
      'examples/pico/modular-gyroid-puzzle.ts',
      'test/examples-pico.test.ts',
    ],
  },
  eslint.configs.recommended,
  {
    files: ['**/*.{cjs,js,mjs}'],
    languageOptions: { globals: globals.node },
  },
  {
    // Browser pages, and Node scripts whose Playwright callbacks run in the page.
    files: [
      'demo/**',
      'scripts/browser-gate.mjs',
      'scripts/emdawnwebgpu-spike.mjs',
      'spikes/webgpu/emdawn/runner.mjs',
      'test/browser/**',
    ],
    languageOptions: { globals: { ...globals.browser, ...globals.worker } },
  },
  {
    files: ['**/*.{ts,mts}'],
    extends: tseslint.configs.strictTypeChecked,
    languageOptions: { parserOptions: { projectService: true } },
    rules: {
      // noUncheckedIndexedAccess is on, and the numeric ports index typed
      // arrays and tuples inside bounds they establish themselves; `!` states
      // that invariant where it holds, as the C# originals index directly.
      '@typescript-eslint/no-non-null-assertion': 'off',
      // `expect(() => session.dispose())` and one-line callbacks return void
      // on purpose.
      '@typescript-eslint/no-confusing-void-expression': ['error', { ignoreArrowShorthand: true }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
    },
  },
  {
    files: ['**/*.{cjs,js,mjs,ts,mts}'],
    plugins: { picovoxel: plugin },
    rules: { 'picovoxel/jsdoc-quality': 'error' },
  },
  {
    // What ships: dist/ is built from these files, so their line comments,
    // thrown messages and every other string reach users too. The C++
    // translation units, the patch headers under patches/ and the proposal
    // files under upstream/ are outside this check: ESLint cannot parse them,
    // and their comments are rewritten together with the upstream proposals
    // they belong to.
    files: ['src/**/*.ts'],
    rules: { 'picovoxel/jsdoc-quality': ['error', { shipped: true }] },
  },
);
