// R9 — generates src/raw.generated.ts from src/abi.json: a typed cwrap table for
// every core export plus this repo's bulk TU additions.
//
// Generating (instead of hand-maintaining) matters for the same reason abi.json is
// generated: a new upstream export appears as a missing binding in the tier-2 gate,
// a renamed one fails to bind, and the known header typos (MetaData_RemoveValue's
// capital D, ScalarField_RemoveValue typed PKVECTORFIELD) are matched, never "fixed".
// Output is deterministic — regenerating over an unchanged abi.json is byte-stable.
//
// Usage: node scripts/generate-raw.mjs  (writes src/raw.generated.ts)

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

/** Handle-typed C types (all uint64_t). Everything else bigint-ish is a count. */
export const HANDLE_TYPES = new Set([
  'PKHANDLE', 'PKINSTANCE', 'PKMESH', 'PKVOXELS', 'PKLATTICE', 'PKPOLYLINE',
  'PKSCALARFIELD', 'PKVECTORFIELD', 'PKVDBFILE', 'PKMETADATA',
]);

/** The bulk TU's own exports (src/picogk-bulk.cpp) — not in upstream's header. */
export const BULK_FUNCTIONS = [
  { name: 'Mesh_GetVertices', cwrapReturn: 'number', args: [
    { name: 'hLib', type: 'PKINSTANCE', cwrap: 'bigint' },
    { name: 'hThis', type: 'PKMESH', cwrap: 'bigint' },
    { name: 'pvecBuffer', type: 'PKVector3*', cwrap: 'number' },
    { name: 'nBufferCount', type: 'int32_t', cwrap: 'number' },
  ] },
  { name: 'Mesh_GetTriangles', cwrapReturn: 'number', args: [
    { name: 'hLib', type: 'PKINSTANCE', cwrap: 'bigint' },
    { name: 'hThis', type: 'PKMESH', cwrap: 'bigint' },
    { name: 'psBuffer', type: 'PKTriangle*', cwrap: 'number' },
    { name: 'nBufferCount', type: 'int32_t', cwrap: 'number' },
  ] },
  { name: 'Mesh_AddVertices', cwrapReturn: 'number', args: [
    { name: 'hLib', type: 'PKINSTANCE', cwrap: 'bigint' },
    { name: 'hThis', type: 'PKMESH', cwrap: 'bigint' },
    { name: 'pvecBuffer', type: 'PKVector3*', cwrap: 'number' },
    { name: 'nCount', type: 'int32_t', cwrap: 'number' },
  ] },
  { name: 'Mesh_AddTriangles', cwrapReturn: 'number', args: [
    { name: 'hLib', type: 'PKINSTANCE', cwrap: 'bigint' },
    { name: 'hThis', type: 'PKMESH', cwrap: 'bigint' },
    { name: 'psBuffer', type: 'PKTriangle*', cwrap: 'number' },
    { name: 'nCount', type: 'int32_t', cwrap: 'number' },
  ] },
];

function tsType(cwrapType, cType) {
  if (cwrapType === null) return 'void';
  if (cwrapType === 'bigint') {
    return HANDLE_TYPES.has((cType ?? '').replace(/\bconst\b/g, '').trim()) ? 'PicoGkHandle' : 'bigint';
  }
  if (cwrapType === 'boolean') return 'boolean';
  return 'number'; // numbers, pointers, enums, callback fn-table indices
}

/** Renders the complete raw.generated.ts source from a parsed abi.json object. */
export function generateRawSource(abi) {
  const core = abi.functions.filter((f) => !f.viewer);
  if (core.length !== 140) {
    throw new Error(`generate-raw: expected 140 core exports, abi.json has ${core.length} — re-run parse-abi and re-read upstream before regenerating`);
  }
  const all = [...core, ...BULK_FUNCTIONS];

  const interfaceLines = all.map((fn) => {
    const params = fn.args.map((a) => `${a.name}: ${tsType(a.cwrap, a.type)}`).join(', ');
    return `  ${fn.name}(${params}): ${tsType(fn.cwrapReturn, fn.returnType)};`;
  });

  const signatureLines = all.map((fn) => {
    const args = fn.args.map((a) => JSON.stringify(a.cwrap === null ? 'number' : a.cwrap)).join(', ');
    return `  ['${fn.name}', ${JSON.stringify(fn.cwrapReturn)}, [${args}]],`;
  });

  return `// GENERATED by scripts/generate-raw.mjs from src/abi.json — do not edit.
// ${core.length} core exports + ${BULK_FUNCTIONS.length} bulk TU additions (src/picogk-bulk.cpp).
// Known upstream header quirks are matched, not fixed: MetaData_RemoveValue (capital
// D), ScalarField_RemoveValue's handle typed PKVECTORFIELD (all handles are uint64_t,
// so it binds by name and works on a scalar field), name-keyed Metadata_*At.

import createPicoGKModuleUntyped from './picogk.mjs';
import type { PicoGkWasmModule } from './types.ts';

/** A PicoGK object handle (uint64_t across the ABI). Never a plain count. */
export type PicoGkHandle = bigint & { readonly __picogkHandle?: never };

export interface PicoGkRaw {
${interfaceLines.join('\n')}
}

const SIGNATURES: ReadonlyArray<readonly [string, string | null, readonly string[]]> = [
${signatureLines.join('\n')}
];

/** Binds every export as a cwrap on an instantiated module. */
export function bindPicoGkRaw(module: PicoGkWasmModule): PicoGkRaw {
  const table: Record<string, unknown> = {};
  for (const [name, returnType, argTypes] of SIGNATURES) {
    table[name] = module.cwrap(name, returnType, argTypes);
  }
  return table as unknown as PicoGkRaw;
}

/** Instantiates the wasm module and binds the full raw surface. */
export async function loadPicoGkRaw(overrides: object = {}): Promise<{ module: PicoGkWasmModule; raw: PicoGkRaw }> {
  const module = await (createPicoGKModuleUntyped as (overrides?: object) => Promise<PicoGkWasmModule>)(overrides);
  return { module, raw: bindPicoGkRaw(module) };
}
`;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const here = fileURLToPath(new URL('..', import.meta.url));
  const abi = JSON.parse(await readFile(new URL('../src/abi.json', import.meta.url), 'utf8'));
  const source = generateRawSource(abi);
  await writeFile(new URL('../src/raw.generated.ts', import.meta.url), source);
  process.stderr.write(`generate-raw: wrote src/raw.generated.ts (${source.length} bytes) from ${here}src/abi.json\n`);
}
