// GENERATED by scripts/generate-wasm-exports.mjs from pico.wasm — do not edit.
// The export names the pico.mjs glue reads from its module (minified by Emscripten).

export const WASM_EXPORTS: readonly string[] = [
  '$', '$a', '$b', 'A', 'Aa', 'Ab', 'Ac', 'B', 'Ba', 'Bb', 'C', 'Ca',
  'Cb', 'D', 'Da', 'Db', 'E', 'Ea', 'Eb', 'F', 'Fa', 'Fb', 'G', 'Ga',
  'Gb', 'H', 'Ha', 'Hb', 'I', 'Ia', 'Ib', 'J', 'Ja', 'Jb', 'K', 'Ka',
  'Kb', 'L', 'La', 'Lb', 'M', 'Ma', 'Mb', 'N', 'Na', 'Nb', 'O', 'Oa',
  'Ob', 'P', 'Pa', 'Pb', 'Q', 'Qa', 'Qb', 'R', 'Ra', 'Rb', 'S', 'Sa',
  'Sb', 'T', 'Ta', 'Tb', 'U', 'Ua', 'Ub', 'V', 'Va', 'Vb', 'W', 'Wa',
  'Wb', 'X', 'Xa', 'Xb', 'Y', 'Ya', 'Yb', 'Z', 'Za', 'Zb', '_', '_a',
  '_b', 'aa', 'ab', 'ac', 'ba', 'bb', 'bc', 'ca', 'cb', 'cc', 'da', 'db',
  'dc', 'ea', 'eb', 'ec', 'fa', 'fb', 'fc', 'ga', 'gb', 'gc', 'ha', 'hb',
  'hc', 'ia', 'ib', 'ic', 'ja', 'jb', 'jc', 'ka', 'kb', 'kc', 'la', 'lb',
  'lc', 'ma', 'mb', 'mc', 'na', 'nb', 'nc', 'oa', 'ob', 'oc', 'pa', 'pb',
  'pc', 'qa', 'qb', 'qc', 'r', 'ra', 'rb', 'rc', 's', 'sa', 'sb', 'sc',
  't', 'ta', 'tb', 'tc', 'u', 'ua', 'ub', 'uc', 'v', 'va', 'vb', 'vc',
  'w', 'wa', 'wb', 'wc', 'x', 'xa', 'xb', 'xc', 'y', 'ya', 'yb', 'yc',
  'z', 'za', 'zb', 'zc',
];
