// GENERATED by scripts/generate-wasm-exports.mjs from pico-multi.wasm — do not edit.
// The export names the pico-multi.mjs glue reads from its module (minified by Emscripten).

export const WASM_EXPORTS: readonly string[] = [
  '$', '$a', '$b', '$c', 'Aa', 'Ab', 'Ac', 'Ba', 'Bb', 'Bc', 'Ca', 'Cb',
  'Cc', 'Da', 'Db', 'Dc', 'Ea', 'Eb', 'Ec', 'F', 'Fa', 'Fb', 'Fc', 'G',
  'Ga', 'Gb', 'Gc', 'H', 'Ha', 'Hb', 'Hc', 'I', 'Ia', 'Ib', 'Ic', 'J',
  'Ja', 'Jb', 'Jc', 'K', 'Ka', 'Kb', 'Kc', 'L', 'La', 'Lb', 'Lc', 'M',
  'Ma', 'Mb', 'Mc', 'N', 'Na', 'Nb', 'Nc', 'O', 'Oa', 'Ob', 'Oc', 'P',
  'Pa', 'Pb', 'Pc', 'Q', 'Qa', 'Qb', 'Qc', 'R', 'Ra', 'Rb', 'Rc', 'S',
  'Sa', 'Sb', 'Sc', 'T', 'Ta', 'Tb', 'Tc', 'U', 'Ua', 'Ub', 'Uc', 'V',
  'Va', 'Vb', 'Vc', 'W', 'Wa', 'Wb', 'Wc', 'X', 'Xa', 'Xb', 'Xc', 'Y',
  'Ya', 'Yb', 'Yc', 'Z', 'Za', 'Zb', 'Zc', '_', '_a', '_b', '_c', 'aa',
  'ab', 'ac', 'ad', 'ba', 'bb', 'bc', 'bd', 'ca', 'cb', 'cc', 'cd', 'da',
  'db', 'dc', 'dd', 'ea', 'eb', 'ec', 'ed', 'fa', 'fb', 'fc', 'fd', 'ga',
  'gb', 'gc', 'gd', 'ha', 'hb', 'hc', 'hd', 'ia', 'ib', 'ic', 'id', 'ja',
  'jb', 'jc', 'jd', 'ka', 'kb', 'kc', 'kd', 'la', 'lb', 'lc', 'ld', 'ma',
  'mb', 'mc', 'md', 'na', 'nb', 'nc', 'nd', 'oa', 'ob', 'oc', 'od', 'pa',
  'pb', 'pc', 'pd', 'qa', 'qb', 'qc', 'qd', 'ra', 'rb', 'rc', 'sa', 'sb',
  'sc', 'ta', 'tb', 'tc', 'ua', 'ub', 'uc', 'va', 'vb', 'vc', 'wa', 'wb',
  'wc', 'xa', 'xb', 'xc', 'ya', 'yb', 'yc', 'za', 'zb', 'zc',
];
