// GENERATED by scripts/generate-raw.mjs from src/abi.json — do not edit.
// 140 core exports + 12 own-TU additions (src/pico-bulk.cpp, src/pico-tape.cpp, src/pico-props.cpp, src/pico-offset.cpp).
// Known upstream header quirks are matched, not fixed: MetaData_RemoveValue (capital
// D), ScalarField_RemoveValue's handle typed PKVECTORFIELD (all handles are uint64_t,
// so it binds by name and works on a scalar field), name-keyed Metadata_*At.
//
// SK-0.2 — every binding is a DIRECT wasm export (`module._Name`); no ccall, no
// cwrap. cwrap only returns the raw export when every argType is 'number'/'boolean',
// and one 'bigint' (any PicoGK handle) demotes it to ccall, which re-resolves the
// export by string key, walks a converter array and saves/restores the stack on
// every call. No marshalling is actually needed: handles are already BigInt,
// pointers/enums/floats/ints are already numbers, and booleans coerce on the way in.
//
// Deliberately glue-free: this module must not import pico.mjs, or the serial
// glue would ride into the picovoxel/multi graph through session.ts. The
// instantiate-and-bind convenience lives in raw.ts (single) beside the entries.

import type { PicoWasmModule } from './types.ts';

/** A PicoGK object handle (uint64_t across the ABI). Never a plain count. */
export type PicoHandle = bigint & { readonly __picoHandle?: never };

export interface PicoRaw {
  Library_GetName(psz: number): void;
  Library_GetVersion(psz: number): void;
  Library_GetBuildInfo(psz: number): void;
  Library_hCreateInstance(fVoxelSizeMM: number): PicoHandle;
  Library_DestroyInstance(hThis: PicoHandle): void;
  Library_nTotalMemUsage(hThis: PicoHandle): bigint;
  Library_nMeshesMemUsage(hThis: PicoHandle): bigint;
  Library_nLatticesMemUsage(hThis: PicoHandle): bigint;
  Library_nPolyLinesMemUsage(hThis: PicoHandle): bigint;
  Library_nVoxelsMemUsage(hThis: PicoHandle): bigint;
  Library_nVdbFilesMemUsage(hThis: PicoHandle): bigint;
  Library_nScalarFieldsMemUsage(hThis: PicoHandle): bigint;
  Library_nVectorFieldsMemUsage(hThis: PicoHandle): bigint;
  Library_nVdbMetasMemUsage(hThis: PicoHandle): bigint;
  Library_nMeshesAllocated(hThis: PicoHandle): bigint;
  Library_nLatticesAllocated(hThis: PicoHandle): bigint;
  Library_nPolyLinesAllocated(hThis: PicoHandle): bigint;
  Library_nVoxelsAllocated(hThis: PicoHandle): bigint;
  Library_nVdbFilesAllocated(hThis: PicoHandle): bigint;
  Library_nScalarFieldsAllocated(hThis: PicoHandle): bigint;
  Library_nVectorFieldsAllocated(hThis: PicoHandle): bigint;
  Library_nVdbMetasAllocated(hThis: PicoHandle): bigint;
  Library_VoxelsToMm(hThis: PicoHandle, pvecVoxelCoordinate: number, pvecMmCoordinate: number): void;
  Library_MmToVoxels(hThis: PicoHandle, pvecMmCoordinate: number, pvecVoxelCoordinate: number): void;
  Mesh_hCreate(hInstance: PicoHandle): PicoHandle;
  Mesh_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  Mesh_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Mesh_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Mesh_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Mesh_nAddVertex(hInstance: PicoHandle, hThis: PicoHandle, pvecVertex: number): number;
  Mesh_nVertexCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Mesh_GetVertex(hInstance: PicoHandle, hThis: PicoHandle, nVertex: number, pvecVertex: number): void;
  Mesh_nAddTriangle(hInstance: PicoHandle, hThis: PicoHandle, psTri: number): number;
  Mesh_nTriangleCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Mesh_GetTriangle(hInstance: PicoHandle, hThis: PicoHandle, nTriangle: number, psTri: number): void;
  Mesh_GetTriangleV(hInstance: PicoHandle, hThis: PicoHandle, nTriangle: number, pvecA: number, pvecB: number, pvecC: number): void;
  Mesh_GetBoundingBox(hInstance: PicoHandle, hThis: PicoHandle, poBox: number): void;
  Lattice_hCreate(hInstance: PicoHandle): PicoHandle;
  Lattice_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Lattice_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Lattice_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Lattice_AddSphere(hInstance: PicoHandle, hThis: PicoHandle, vecCenter: number, fRadius: number): void;
  Lattice_AddBeam(hInstance: PicoHandle, hThis: PicoHandle, pvecA: number, pvecB: number, fRadiusA: number, fRadiusB: number, bRoundCap: boolean): void;
  Voxels_hCreate(hInstance: PicoHandle): PicoHandle;
  Voxels_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  Voxels_hCreateSphere(hInstance: PicoHandle, pvecCenter: number, fRadius: number): PicoHandle;
  Voxels_hCreateCapsule(hInstance: PicoHandle, pvecStart: number, pvecStop: number, fRadius1: number, fRadius2: number): PicoHandle;
  Voxels_hCreateMeshShell(hLib: PicoHandle, hMesh: PicoHandle, fRadius: number): PicoHandle;
  Voxels_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Voxels_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Voxels_bDiagnose(hInstance: PicoHandle, hThis: PicoHandle, psz: number): boolean;
  Voxels_bIsEmpty(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Voxels_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Voxels_fVoxelSize(hInstance: PicoHandle, hVoxels: PicoHandle): number;
  Voxels_BoolAdd(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_BoolSubtract(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_BoolIntersect(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_Offset(hInstance: PicoHandle, hThis: PicoHandle, fDist: number): void;
  Voxels_DoubleOffset(hInstance: PicoHandle, hThis: PicoHandle, fDist1: number, fDist2: number): void;
  Voxels_TripleOffset(hInstance: PicoHandle, hThis: PicoHandle, fDist: number): void;
  Voxels_RenderMesh(hInstance: PicoHandle, hThis: PicoHandle, hMesh: PicoHandle): void;
  Voxels_RenderImplicit(hInstance: PicoHandle, hThis: PicoHandle, poBBox: number, pfnSDF: number): void;
  Voxels_IntersectImplicit(hInstance: PicoHandle, hThis: PicoHandle, pfnSDF: number): void;
  Voxels_RenderLattice(hInstance: PicoHandle, hThis: PicoHandle, hLattice: PicoHandle): void;
  Voxels_ProjectZSlice(hInstance: PicoHandle, hThis: PicoHandle, fStartZ: number, fEndZ: number): void;
  Voxels_bIsInside(hInstance: PicoHandle, hThis: PicoHandle, pvecTestPoint: number): boolean;
  Voxels_bIsEqual(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): boolean;
  Voxels_fCalculateVolume(hInstance: PicoHandle, hThis: PicoHandle): number;
  Voxels_GetSurfaceNormal(hInstance: PicoHandle, hThis: PicoHandle, pvecSurfacePoint: number, pvecNormal: number): void;
  Voxels_bClosestPointOnSurface(hInstance: PicoHandle, hThis: PicoHandle, pvecSearch: number, pvecSurfacePoint: number): boolean;
  Voxels_bRayCastToSurface(hInstance: PicoHandle, hThis: PicoHandle, pvecSearch: number, pvecDirection: number, pvecSurfacePoint: number): boolean;
  Voxels_GetVoxelDimensions(hInstance: PicoHandle, hThis: PicoHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  Voxels_GetXSlice(hInstance: PicoHandle, hThis: PicoHandle, nXSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetYSlice(hInstance: PicoHandle, hThis: PicoHandle, nYSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetZSlice(hInstance: PicoHandle, hThis: PicoHandle, nZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetInterpolatedZSlice(hLib: PicoHandle, hThis: PicoHandle, fZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  PolyLine_hCreate(hInstance: PicoHandle, pclr: number): PicoHandle;
  PolyLine_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  PolyLine_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  PolyLine_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  PolyLine_nAddVertex(hInstance: PicoHandle, hThis: PicoHandle, pvec: number): number;
  PolyLine_nVertexCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  PolyLine_GetVertex(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number, pvec: number): void;
  PolyLine_GetColor(hInstance: PicoHandle, hThis: PicoHandle, pclr: number): void;
  PolyLine_GetBoundingBox(hLib: PicoHandle, hThis: PicoHandle, poBox: number): void;
  VdbFile_hCreate(hInstance: PicoHandle): PicoHandle;
  VdbFile_hCreateFromFile(hInstance: PicoHandle, pszFileName: number): PicoHandle;
  VdbFile_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  VdbFile_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  VdbFile_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  VdbFile_bSaveToFile(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFileName: number): boolean;
  VdbFile_hGetVoxels(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddVoxels(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hVoxels: PicoHandle): number;
  VdbFile_hGetScalarField(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddScalarField(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hScalarField: PicoHandle): number;
  VdbFile_hGetVectorField(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddVectorField(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hVectorField: PicoHandle): number;
  VdbFile_nFieldCount(hInstance: PicoHandle, hVdbFile: PicoHandle): number;
  VdbFile_GetFieldName(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number, psz: number): void;
  VdbFile_nFieldType(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): number;
  ScalarField_hCreate(hInstance: PicoHandle): PicoHandle;
  ScalarField_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  ScalarField_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  ScalarField_hBuildFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle, fScalarValue: number, fSdThreshold: number): PicoHandle;
  ScalarField_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  ScalarField_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  ScalarField_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  ScalarField_SetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, fValue: number): void;
  ScalarField_bGetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pfValue: number): boolean;
  ScalarField_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number): void;
  ScalarField_GetVoxelDimensions(hInstance: PicoHandle, hThis: PicoHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  ScalarField_GetSlice(hInstance: PicoHandle, hThis: PicoHandle, nZSlice: number, pfBuffer: number): void;
  ScalarField_TraverseActive(hInstance: PicoHandle, hThis: PicoHandle, pfnCallback: number): void;
  VectorField_hCreate(hInstance: PicoHandle): PicoHandle;
  VectorField_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  VectorField_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  VectorField_hBuildFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle, vecValue: number, fSdThreshold: number): PicoHandle;
  VectorField_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  VectorField_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  VectorField_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  VectorField_SetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pvecValue: number): void;
  VectorField_bGetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pvecValue: number): boolean;
  VectorField_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number): void;
  VectorField_TraverseActive(hInstance: PicoHandle, hThis: PicoHandle, pfnCallback: number): void;
  Metadata_hFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  Metadata_hFromScalarField(hInstance: PicoHandle, hScalarField: PicoHandle): PicoHandle;
  Metadata_hFromVectorField(hInstance: PicoHandle, hVectorField: PicoHandle): PicoHandle;
  Metadata_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Metadata_nCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Metadata_nNameLengthAt(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number): number;
  Metadata_bGetNameAt(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number, psz: number, nMaxStringLen: number): boolean;
  Metadata_nTypeAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number): number;
  Metadata_nStringLengthAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number): number;
  Metadata_bGetStringAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pszValue: number, nMaxStringLen: number): boolean;
  Metadata_bGetFloatAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pfValue: number): boolean;
  Metadata_bGetVectorAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pvecValue: number): boolean;
  Metadata_SetStringValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, pszValue: number): void;
  Metadata_SetFloatValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, fValue: number): void;
  Metadata_SetVectorValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, pvecValue: number): void;
  MetaData_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number): void;
  Mesh_GetVertices(hLib: PicoHandle, hThis: PicoHandle, pvecBuffer: number, nBufferCount: number): number;
  Mesh_GetTriangles(hLib: PicoHandle, hThis: PicoHandle, psBuffer: number, nBufferCount: number): number;
  Mesh_AddVertices(hLib: PicoHandle, hThis: PicoHandle, pvecBuffer: number, nCount: number): number;
  Mesh_AddTriangles(hLib: PicoHandle, hThis: PicoHandle, psBuffer: number, nCount: number): number;
  Voxels_RenderImplicitTape(hLib: PicoHandle, hThis: PicoHandle, poBBox: number, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
  Voxels_RenderImplicitTapeCompose(hLib: PicoHandle, hThis: PicoHandle, poBBox: number, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
  Lattice_AddBeams(hLib: PicoHandle, hThis: PicoHandle, pfBeams: number, pnRoundCap: number, nCount: number): number;
  Lattice_AddSpheres(hLib: PicoHandle, hThis: PicoHandle, pfSpheres: number, nCount: number): number;
  Voxels_GetProperties(hLib: PicoHandle, hThis: PicoHandle, pfVolume: number, pfArea: number, poBBox: number): void;
  Voxels_OffsetTuned(hLib: PicoHandle, hThis: PicoHandle, pfDistancesMM: number, nCount: number, nSpatialScheme: number, nNormCount: number): void;
  Voxels_RenderLatticeTubes(hLib: PicoHandle, hThis: PicoHandle, hLattice: PicoHandle): void;
  Voxels_IntersectImplicitTape(hLib: PicoHandle, hThis: PicoHandle, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
}

/** Everything crossing this ABI: a number (pointer/enum/float/int), a uint64 handle, or a bool. */
type AbiValue = number | bigint | boolean;
type WasmExport = (...args: AbiValue[]) => unknown;

const EXPORTS: readonly string[] = [
  'Library_GetName',
  'Library_GetVersion',
  'Library_GetBuildInfo',
  'Library_hCreateInstance',
  'Library_DestroyInstance',
  'Library_nTotalMemUsage',
  'Library_nMeshesMemUsage',
  'Library_nLatticesMemUsage',
  'Library_nPolyLinesMemUsage',
  'Library_nVoxelsMemUsage',
  'Library_nVdbFilesMemUsage',
  'Library_nScalarFieldsMemUsage',
  'Library_nVectorFieldsMemUsage',
  'Library_nVdbMetasMemUsage',
  'Library_nMeshesAllocated',
  'Library_nLatticesAllocated',
  'Library_nPolyLinesAllocated',
  'Library_nVoxelsAllocated',
  'Library_nVdbFilesAllocated',
  'Library_nScalarFieldsAllocated',
  'Library_nVectorFieldsAllocated',
  'Library_nVdbMetasAllocated',
  'Library_VoxelsToMm',
  'Library_MmToVoxels',
  'Mesh_hCreate',
  'Mesh_hCreateFromVoxels',
  'Mesh_bIsValid',
  'Mesh_Destroy',
  'Mesh_nMemUsage',
  'Mesh_nAddVertex',
  'Mesh_nVertexCount',
  'Mesh_GetVertex',
  'Mesh_nAddTriangle',
  'Mesh_nTriangleCount',
  'Mesh_GetTriangle',
  'Mesh_GetTriangleV',
  'Mesh_GetBoundingBox',
  'Lattice_hCreate',
  'Lattice_nMemUsage',
  'Lattice_bIsValid',
  'Lattice_Destroy',
  'Lattice_AddSphere',
  'Lattice_AddBeam',
  'Voxels_hCreate',
  'Voxels_hCreateCopy',
  'Voxels_hCreateSphere',
  'Voxels_hCreateCapsule',
  'Voxels_hCreateMeshShell',
  'Voxels_bIsValid',
  'Voxels_Destroy',
  'Voxels_bDiagnose',
  'Voxels_bIsEmpty',
  'Voxels_nMemUsage',
  'Voxels_fVoxelSize',
  'Voxels_BoolAdd',
  'Voxels_BoolSubtract',
  'Voxels_BoolIntersect',
  'Voxels_Offset',
  'Voxels_DoubleOffset',
  'Voxels_TripleOffset',
  'Voxels_RenderMesh',
  'Voxels_RenderImplicit',
  'Voxels_IntersectImplicit',
  'Voxels_RenderLattice',
  'Voxels_ProjectZSlice',
  'Voxels_bIsInside',
  'Voxels_bIsEqual',
  'Voxels_fCalculateVolume',
  'Voxels_GetSurfaceNormal',
  'Voxels_bClosestPointOnSurface',
  'Voxels_bRayCastToSurface',
  'Voxels_GetVoxelDimensions',
  'Voxels_GetXSlice',
  'Voxels_GetYSlice',
  'Voxels_GetZSlice',
  'Voxels_GetInterpolatedZSlice',
  'PolyLine_hCreate',
  'PolyLine_bIsValid',
  'PolyLine_Destroy',
  'PolyLine_nMemUsage',
  'PolyLine_nAddVertex',
  'PolyLine_nVertexCount',
  'PolyLine_GetVertex',
  'PolyLine_GetColor',
  'PolyLine_GetBoundingBox',
  'VdbFile_hCreate',
  'VdbFile_hCreateFromFile',
  'VdbFile_bIsValid',
  'VdbFile_Destroy',
  'VdbFile_nMemUsage',
  'VdbFile_bSaveToFile',
  'VdbFile_hGetVoxels',
  'VdbFile_nAddVoxels',
  'VdbFile_hGetScalarField',
  'VdbFile_nAddScalarField',
  'VdbFile_hGetVectorField',
  'VdbFile_nAddVectorField',
  'VdbFile_nFieldCount',
  'VdbFile_GetFieldName',
  'VdbFile_nFieldType',
  'ScalarField_hCreate',
  'ScalarField_hCreateCopy',
  'ScalarField_hCreateFromVoxels',
  'ScalarField_hBuildFromVoxels',
  'ScalarField_bIsValid',
  'ScalarField_Destroy',
  'ScalarField_nMemUsage',
  'ScalarField_SetValue',
  'ScalarField_bGetValue',
  'ScalarField_RemoveValue',
  'ScalarField_GetVoxelDimensions',
  'ScalarField_GetSlice',
  'ScalarField_TraverseActive',
  'VectorField_hCreate',
  'VectorField_hCreateCopy',
  'VectorField_hCreateFromVoxels',
  'VectorField_hBuildFromVoxels',
  'VectorField_bIsValid',
  'VectorField_Destroy',
  'VectorField_nMemUsage',
  'VectorField_SetValue',
  'VectorField_bGetValue',
  'VectorField_RemoveValue',
  'VectorField_TraverseActive',
  'Metadata_hFromVoxels',
  'Metadata_hFromScalarField',
  'Metadata_hFromVectorField',
  'Metadata_Destroy',
  'Metadata_nCount',
  'Metadata_nNameLengthAt',
  'Metadata_bGetNameAt',
  'Metadata_nTypeAt',
  'Metadata_nStringLengthAt',
  'Metadata_bGetStringAt',
  'Metadata_bGetFloatAt',
  'Metadata_bGetVectorAt',
  'Metadata_SetStringValue',
  'Metadata_SetFloatValue',
  'Metadata_SetVectorValue',
  'MetaData_RemoveValue',
  'Mesh_GetVertices',
  'Mesh_GetTriangles',
  'Mesh_AddVertices',
  'Mesh_AddTriangles',
  'Voxels_RenderImplicitTape',
  'Voxels_RenderImplicitTapeCompose',
  'Lattice_AddBeams',
  'Lattice_AddSpheres',
  'Voxels_GetProperties',
  'Voxels_OffsetTuned',
  'Voxels_RenderLatticeTubes',
  'Voxels_IntersectImplicitTape',
];

/** i32 -> boolean at the boundary — the one thing the raw export cannot do itself. */
const BOOLEAN_RETURNS: Readonly<Record<string, (fn: WasmExport) => WasmExport>> = {
  Mesh_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  Lattice_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  Voxels_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  Voxels_bDiagnose: (fn) => (a0, a1, a2) => !!fn(a0, a1, a2),
  Voxels_bIsEmpty: (fn) => (a0, a1) => !!fn(a0, a1),
  Voxels_bIsInside: (fn) => (a0, a1, a2) => !!fn(a0, a1, a2),
  Voxels_bIsEqual: (fn) => (a0, a1, a2) => !!fn(a0, a1, a2),
  Voxels_bClosestPointOnSurface: (fn) => (a0, a1, a2, a3) => !!fn(a0, a1, a2, a3),
  Voxels_bRayCastToSurface: (fn) => (a0, a1, a2, a3, a4) => !!fn(a0, a1, a2, a3, a4),
  PolyLine_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  VdbFile_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  VdbFile_bSaveToFile: (fn) => (a0, a1, a2) => !!fn(a0, a1, a2),
  ScalarField_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  ScalarField_bGetValue: (fn) => (a0, a1, a2, a3) => !!fn(a0, a1, a2, a3),
  VectorField_bIsValid: (fn) => (a0, a1) => !!fn(a0, a1),
  VectorField_bGetValue: (fn) => (a0, a1, a2, a3) => !!fn(a0, a1, a2, a3),
  Metadata_bGetNameAt: (fn) => (a0, a1, a2, a3, a4) => !!fn(a0, a1, a2, a3, a4),
  Metadata_bGetStringAt: (fn) => (a0, a1, a2, a3, a4) => !!fn(a0, a1, a2, a3, a4),
  Metadata_bGetFloatAt: (fn) => (a0, a1, a2, a3) => !!fn(a0, a1, a2, a3),
  Metadata_bGetVectorAt: (fn) => (a0, a1, a2, a3) => !!fn(a0, a1, a2, a3),
};

/** Binds every export as a direct wasm call on an instantiated module. */
export function bindPicoRaw(module: PicoWasmModule): PicoRaw {
  const exports = module as unknown as Record<string, WasmExport | undefined>;
  const table: Record<string, WasmExport> = {};
  for (const name of EXPORTS) {
    const fn = exports[`_${name}`];
    if (typeof fn !== 'function') {
      throw new Error(
        `picovoxel: the wasm module exports no _${name}. Rebuild with scripts/build-pico-module.sh — ` +
          'src/pico-exports.txt is the EXPORTED_FUNCTIONS list this binding table expects.',
      );
    }
    const toBoolean = BOOLEAN_RETURNS[name];
    table[name] = toBoolean ? toBoolean(fn) : fn;
  }
  return table as unknown as PicoRaw;
}
