// GENERATED by scripts/generate-raw.mjs from src/abi.json — do not edit.
// 140 core exports + 5 own-TU additions (src/picogk-bulk.cpp, src/picogk-tape.cpp).
// Known upstream header quirks are matched, not fixed: MetaData_RemoveValue (capital
// D), ScalarField_RemoveValue's handle typed PKVECTORFIELD (all handles are uint64_t,
// so it binds by name and works on a scalar field), name-keyed Metadata_*At.
//
// Deliberately glue-free: this module must not import picogk.mjs, or the serial
// glue would ride into the picogk-js/multi graph through session.ts. The
// instantiate-and-bind convenience lives in raw.ts (single) beside the entries.

import type { PicoGkWasmModule } from './types.ts';

/** A PicoGK object handle (uint64_t across the ABI). Never a plain count. */
export type PicoGkHandle = bigint & { readonly __picogkHandle?: never };

export interface PicoGkRaw {
  Library_GetName(psz: number): void;
  Library_GetVersion(psz: number): void;
  Library_GetBuildInfo(psz: number): void;
  Library_hCreateInstance(fVoxelSizeMM: number): PicoGkHandle;
  Library_DestroyInstance(hThis: PicoGkHandle): void;
  Library_nTotalMemUsage(hThis: PicoGkHandle): bigint;
  Library_nMeshesMemUsage(hThis: PicoGkHandle): bigint;
  Library_nLatticesMemUsage(hThis: PicoGkHandle): bigint;
  Library_nPolyLinesMemUsage(hThis: PicoGkHandle): bigint;
  Library_nVoxelsMemUsage(hThis: PicoGkHandle): bigint;
  Library_nVdbFilesMemUsage(hThis: PicoGkHandle): bigint;
  Library_nScalarFieldsMemUsage(hThis: PicoGkHandle): bigint;
  Library_nVectorFieldsMemUsage(hThis: PicoGkHandle): bigint;
  Library_nVdbMetasMemUsage(hThis: PicoGkHandle): bigint;
  Library_nMeshesAllocated(hThis: PicoGkHandle): bigint;
  Library_nLatticesAllocated(hThis: PicoGkHandle): bigint;
  Library_nPolyLinesAllocated(hThis: PicoGkHandle): bigint;
  Library_nVoxelsAllocated(hThis: PicoGkHandle): bigint;
  Library_nVdbFilesAllocated(hThis: PicoGkHandle): bigint;
  Library_nScalarFieldsAllocated(hThis: PicoGkHandle): bigint;
  Library_nVectorFieldsAllocated(hThis: PicoGkHandle): bigint;
  Library_nVdbMetasAllocated(hThis: PicoGkHandle): bigint;
  Library_VoxelsToMm(hThis: PicoGkHandle, pvecVoxelCoordinate: number, pvecMmCoordinate: number): void;
  Library_MmToVoxels(hThis: PicoGkHandle, pvecMmCoordinate: number, pvecVoxelCoordinate: number): void;
  Mesh_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  Mesh_hCreateFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle): PicoGkHandle;
  Mesh_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  Mesh_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  Mesh_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  Mesh_nAddVertex(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecVertex: number): number;
  Mesh_nVertexCount(hInstance: PicoGkHandle, hThis: PicoGkHandle): number;
  Mesh_GetVertex(hInstance: PicoGkHandle, hThis: PicoGkHandle, nVertex: number, pvecVertex: number): void;
  Mesh_nAddTriangle(hInstance: PicoGkHandle, hThis: PicoGkHandle, psTri: number): number;
  Mesh_nTriangleCount(hInstance: PicoGkHandle, hThis: PicoGkHandle): number;
  Mesh_GetTriangle(hInstance: PicoGkHandle, hThis: PicoGkHandle, nTriangle: number, psTri: number): void;
  Mesh_GetTriangleV(hInstance: PicoGkHandle, hThis: PicoGkHandle, nTriangle: number, pvecA: number, pvecB: number, pvecC: number): void;
  Mesh_GetBoundingBox(hInstance: PicoGkHandle, hThis: PicoGkHandle, poBox: number): void;
  Lattice_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  Lattice_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  Lattice_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  Lattice_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  Lattice_AddSphere(hInstance: PicoGkHandle, hThis: PicoGkHandle, vecCenter: number, fRadius: number): void;
  Lattice_AddBeam(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecA: number, pvecB: number, fRadiusA: number, fRadiusB: number, bRoundCap: boolean): void;
  Voxels_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  Voxels_hCreateCopy(hInstance: PicoGkHandle, hSource: PicoGkHandle): PicoGkHandle;
  Voxels_hCreateSphere(hInstance: PicoGkHandle, pvecCenter: number, fRadius: number): PicoGkHandle;
  Voxels_hCreateCapsule(hInstance: PicoGkHandle, pvecStart: number, pvecStop: number, fRadius1: number, fRadius2: number): PicoGkHandle;
  Voxels_hCreateMeshShell(hLib: PicoGkHandle, hMesh: PicoGkHandle, fRadius: number): PicoGkHandle;
  Voxels_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  Voxels_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  Voxels_bDiagnose(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number): boolean;
  Voxels_bIsEmpty(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  Voxels_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  Voxels_fVoxelSize(hInstance: PicoGkHandle, hVoxels: PicoGkHandle): number;
  Voxels_BoolAdd(hInstance: PicoGkHandle, hThis: PicoGkHandle, hOther: PicoGkHandle): void;
  Voxels_BoolSubtract(hInstance: PicoGkHandle, hThis: PicoGkHandle, hOther: PicoGkHandle): void;
  Voxels_BoolIntersect(hInstance: PicoGkHandle, hThis: PicoGkHandle, hOther: PicoGkHandle): void;
  Voxels_Offset(hInstance: PicoGkHandle, hThis: PicoGkHandle, fDist: number): void;
  Voxels_DoubleOffset(hInstance: PicoGkHandle, hThis: PicoGkHandle, fDist1: number, fDist2: number): void;
  Voxels_TripleOffset(hInstance: PicoGkHandle, hThis: PicoGkHandle, fDist: number): void;
  Voxels_RenderMesh(hInstance: PicoGkHandle, hThis: PicoGkHandle, hMesh: PicoGkHandle): void;
  Voxels_RenderImplicit(hInstance: PicoGkHandle, hThis: PicoGkHandle, poBBox: number, pfnSDF: number): void;
  Voxels_IntersectImplicit(hInstance: PicoGkHandle, hThis: PicoGkHandle, pfnSDF: number): void;
  Voxels_RenderLattice(hInstance: PicoGkHandle, hThis: PicoGkHandle, hLattice: PicoGkHandle): void;
  Voxels_ProjectZSlice(hInstance: PicoGkHandle, hThis: PicoGkHandle, fStartZ: number, fEndZ: number): void;
  Voxels_bIsInside(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecTestPoint: number): boolean;
  Voxels_bIsEqual(hInstance: PicoGkHandle, hThis: PicoGkHandle, hOther: PicoGkHandle): boolean;
  Voxels_fCalculateVolume(hInstance: PicoGkHandle, hThis: PicoGkHandle): number;
  Voxels_GetSurfaceNormal(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecSurfacePoint: number, pvecNormal: number): void;
  Voxels_bClosestPointOnSurface(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecSearch: number, pvecSurfacePoint: number): boolean;
  Voxels_bRayCastToSurface(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecSearch: number, pvecDirection: number, pvecSurfacePoint: number): boolean;
  Voxels_GetVoxelDimensions(hInstance: PicoGkHandle, hThis: PicoGkHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  Voxels_GetXSlice(hInstance: PicoGkHandle, hThis: PicoGkHandle, nXSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetYSlice(hInstance: PicoGkHandle, hThis: PicoGkHandle, nYSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetZSlice(hInstance: PicoGkHandle, hThis: PicoGkHandle, nZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetInterpolatedZSlice(hLib: PicoGkHandle, hThis: PicoGkHandle, fZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  PolyLine_hCreate(hInstance: PicoGkHandle, pclr: number): PicoGkHandle;
  PolyLine_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  PolyLine_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  PolyLine_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  PolyLine_nAddVertex(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvec: number): number;
  PolyLine_nVertexCount(hInstance: PicoGkHandle, hThis: PicoGkHandle): number;
  PolyLine_GetVertex(hInstance: PicoGkHandle, hThis: PicoGkHandle, nIndex: number, pvec: number): void;
  PolyLine_GetColor(hInstance: PicoGkHandle, hThis: PicoGkHandle, pclr: number): void;
  PolyLine_GetBoundingBox(hLib: PicoGkHandle, hThis: PicoGkHandle, poBox: number): void;
  VdbFile_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  VdbFile_hCreateFromFile(hInstance: PicoGkHandle, pszFileName: number): PicoGkHandle;
  VdbFile_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  VdbFile_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  VdbFile_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  VdbFile_bSaveToFile(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, pszFileName: number): boolean;
  VdbFile_hGetVoxels(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, nIndex: number): PicoGkHandle;
  VdbFile_nAddVoxels(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, pszFieldName: number, hVoxels: PicoGkHandle): number;
  VdbFile_hGetScalarField(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, nIndex: number): PicoGkHandle;
  VdbFile_nAddScalarField(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, pszFieldName: number, hScalarField: PicoGkHandle): number;
  VdbFile_hGetVectorField(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, nIndex: number): PicoGkHandle;
  VdbFile_nAddVectorField(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, pszFieldName: number, hVectorField: PicoGkHandle): number;
  VdbFile_nFieldCount(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle): number;
  VdbFile_GetFieldName(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, nIndex: number, psz: number): void;
  VdbFile_nFieldType(hInstance: PicoGkHandle, hVdbFile: PicoGkHandle, nIndex: number): number;
  ScalarField_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  ScalarField_hCreateCopy(hInstance: PicoGkHandle, hSource: PicoGkHandle): PicoGkHandle;
  ScalarField_hCreateFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle): PicoGkHandle;
  ScalarField_hBuildFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle, fScalarValue: number, fSdThreshold: number): PicoGkHandle;
  ScalarField_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  ScalarField_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  ScalarField_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  ScalarField_SetValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number, fValue: number): void;
  ScalarField_bGetValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number, pfValue: number): boolean;
  ScalarField_RemoveValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number): void;
  ScalarField_GetVoxelDimensions(hInstance: PicoGkHandle, hThis: PicoGkHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  ScalarField_GetSlice(hInstance: PicoGkHandle, hThis: PicoGkHandle, nZSlice: number, pfBuffer: number): void;
  ScalarField_TraverseActive(hInstance: PicoGkHandle, hThis: PicoGkHandle, pfnCallback: number): void;
  VectorField_hCreate(hInstance: PicoGkHandle): PicoGkHandle;
  VectorField_hCreateCopy(hInstance: PicoGkHandle, hSource: PicoGkHandle): PicoGkHandle;
  VectorField_hCreateFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle): PicoGkHandle;
  VectorField_hBuildFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle, vecValue: number, fSdThreshold: number): PicoGkHandle;
  VectorField_bIsValid(hInstance: PicoGkHandle, hThis: PicoGkHandle): boolean;
  VectorField_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  VectorField_nMemUsage(hInstance: PicoGkHandle, hThis: PicoGkHandle): bigint;
  VectorField_SetValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number, pvecValue: number): void;
  VectorField_bGetValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number, pvecValue: number): boolean;
  VectorField_RemoveValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pvecPosition: number): void;
  VectorField_TraverseActive(hInstance: PicoGkHandle, hThis: PicoGkHandle, pfnCallback: number): void;
  Metadata_hFromVoxels(hInstance: PicoGkHandle, hVoxels: PicoGkHandle): PicoGkHandle;
  Metadata_hFromScalarField(hInstance: PicoGkHandle, hScalarField: PicoGkHandle): PicoGkHandle;
  Metadata_hFromVectorField(hInstance: PicoGkHandle, hVectorField: PicoGkHandle): PicoGkHandle;
  Metadata_Destroy(hInstance: PicoGkHandle, hThis: PicoGkHandle): void;
  Metadata_nCount(hInstance: PicoGkHandle, hThis: PicoGkHandle): number;
  Metadata_nNameLengthAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, nIndex: number): number;
  Metadata_bGetNameAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, nIndex: number, psz: number, nMaxStringLen: number): boolean;
  Metadata_nTypeAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number): number;
  Metadata_nStringLengthAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number): number;
  Metadata_bGetStringAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number, pszValue: number, nMaxStringLen: number): boolean;
  Metadata_bGetFloatAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number, pfValue: number): boolean;
  Metadata_bGetVectorAt(hInstance: PicoGkHandle, hThis: PicoGkHandle, psz: number, pvecValue: number): boolean;
  Metadata_SetStringValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pszFieldName: number, pszValue: number): void;
  Metadata_SetFloatValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pszFieldName: number, fValue: number): void;
  Metadata_SetVectorValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pszFieldName: number, pvecValue: number): void;
  MetaData_RemoveValue(hInstance: PicoGkHandle, hThis: PicoGkHandle, pszFieldName: number): void;
  Mesh_GetVertices(hLib: PicoGkHandle, hThis: PicoGkHandle, pvecBuffer: number, nBufferCount: number): number;
  Mesh_GetTriangles(hLib: PicoGkHandle, hThis: PicoGkHandle, psBuffer: number, nBufferCount: number): number;
  Mesh_AddVertices(hLib: PicoGkHandle, hThis: PicoGkHandle, pvecBuffer: number, nCount: number): number;
  Mesh_AddTriangles(hLib: PicoGkHandle, hThis: PicoGkHandle, psBuffer: number, nCount: number): number;
  Voxels_RenderImplicitTape(hLib: PicoGkHandle, hThis: PicoGkHandle, poBBox: number, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
}

const SIGNATURES: ReadonlyArray<readonly [string, string | null, readonly string[]]> = [
  ['Library_GetName', null, ["number"]],
  ['Library_GetVersion', null, ["number"]],
  ['Library_GetBuildInfo', null, ["number"]],
  ['Library_hCreateInstance', "bigint", ["number"]],
  ['Library_DestroyInstance', null, ["bigint"]],
  ['Library_nTotalMemUsage', "bigint", ["bigint"]],
  ['Library_nMeshesMemUsage', "bigint", ["bigint"]],
  ['Library_nLatticesMemUsage', "bigint", ["bigint"]],
  ['Library_nPolyLinesMemUsage', "bigint", ["bigint"]],
  ['Library_nVoxelsMemUsage', "bigint", ["bigint"]],
  ['Library_nVdbFilesMemUsage', "bigint", ["bigint"]],
  ['Library_nScalarFieldsMemUsage', "bigint", ["bigint"]],
  ['Library_nVectorFieldsMemUsage', "bigint", ["bigint"]],
  ['Library_nVdbMetasMemUsage', "bigint", ["bigint"]],
  ['Library_nMeshesAllocated', "bigint", ["bigint"]],
  ['Library_nLatticesAllocated', "bigint", ["bigint"]],
  ['Library_nPolyLinesAllocated', "bigint", ["bigint"]],
  ['Library_nVoxelsAllocated', "bigint", ["bigint"]],
  ['Library_nVdbFilesAllocated', "bigint", ["bigint"]],
  ['Library_nScalarFieldsAllocated', "bigint", ["bigint"]],
  ['Library_nVectorFieldsAllocated', "bigint", ["bigint"]],
  ['Library_nVdbMetasAllocated', "bigint", ["bigint"]],
  ['Library_VoxelsToMm', null, ["bigint", "number", "number"]],
  ['Library_MmToVoxels', null, ["bigint", "number", "number"]],
  ['Mesh_hCreate', "bigint", ["bigint"]],
  ['Mesh_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['Mesh_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Mesh_Destroy', null, ["bigint", "bigint"]],
  ['Mesh_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Mesh_nAddVertex', "number", ["bigint", "bigint", "number"]],
  ['Mesh_nVertexCount', "number", ["bigint", "bigint"]],
  ['Mesh_GetVertex', null, ["bigint", "bigint", "number", "number"]],
  ['Mesh_nAddTriangle', "number", ["bigint", "bigint", "number"]],
  ['Mesh_nTriangleCount', "number", ["bigint", "bigint"]],
  ['Mesh_GetTriangle', null, ["bigint", "bigint", "number", "number"]],
  ['Mesh_GetTriangleV', null, ["bigint", "bigint", "number", "number", "number", "number"]],
  ['Mesh_GetBoundingBox', null, ["bigint", "bigint", "number"]],
  ['Lattice_hCreate', "bigint", ["bigint"]],
  ['Lattice_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Lattice_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Lattice_Destroy', null, ["bigint", "bigint"]],
  ['Lattice_AddSphere', null, ["bigint", "bigint", "number", "number"]],
  ['Lattice_AddBeam', null, ["bigint", "bigint", "number", "number", "number", "number", "boolean"]],
  ['Voxels_hCreate', "bigint", ["bigint"]],
  ['Voxels_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['Voxels_hCreateSphere', "bigint", ["bigint", "number", "number"]],
  ['Voxels_hCreateCapsule', "bigint", ["bigint", "number", "number", "number", "number"]],
  ['Voxels_hCreateMeshShell', "bigint", ["bigint", "bigint", "number"]],
  ['Voxels_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Voxels_Destroy', null, ["bigint", "bigint"]],
  ['Voxels_bDiagnose', "boolean", ["bigint", "bigint", "number"]],
  ['Voxels_bIsEmpty', "boolean", ["bigint", "bigint"]],
  ['Voxels_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Voxels_fVoxelSize', "number", ["bigint", "bigint"]],
  ['Voxels_BoolAdd', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_BoolSubtract', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_BoolIntersect', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_Offset', null, ["bigint", "bigint", "number"]],
  ['Voxels_DoubleOffset', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_TripleOffset', null, ["bigint", "bigint", "number"]],
  ['Voxels_RenderMesh', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_RenderImplicit', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_IntersectImplicit', null, ["bigint", "bigint", "number"]],
  ['Voxels_RenderLattice', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_ProjectZSlice', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_bIsInside', "boolean", ["bigint", "bigint", "number"]],
  ['Voxels_bIsEqual', "boolean", ["bigint", "bigint", "bigint"]],
  ['Voxels_fCalculateVolume', "number", ["bigint", "bigint"]],
  ['Voxels_GetSurfaceNormal', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_bClosestPointOnSurface', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Voxels_bRayCastToSurface', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetVoxelDimensions', null, ["bigint", "bigint", "number", "number", "number", "number", "number", "number"]],
  ['Voxels_GetXSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetYSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetZSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetInterpolatedZSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['PolyLine_hCreate', "bigint", ["bigint", "number"]],
  ['PolyLine_bIsValid', "boolean", ["bigint", "bigint"]],
  ['PolyLine_Destroy', null, ["bigint", "bigint"]],
  ['PolyLine_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['PolyLine_nAddVertex', "number", ["bigint", "bigint", "number"]],
  ['PolyLine_nVertexCount', "number", ["bigint", "bigint"]],
  ['PolyLine_GetVertex', null, ["bigint", "bigint", "number", "number"]],
  ['PolyLine_GetColor', null, ["bigint", "bigint", "number"]],
  ['PolyLine_GetBoundingBox', null, ["bigint", "bigint", "number"]],
  ['VdbFile_hCreate', "bigint", ["bigint"]],
  ['VdbFile_hCreateFromFile', "bigint", ["bigint", "number"]],
  ['VdbFile_bIsValid', "boolean", ["bigint", "bigint"]],
  ['VdbFile_Destroy', null, ["bigint", "bigint"]],
  ['VdbFile_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['VdbFile_bSaveToFile', "boolean", ["bigint", "bigint", "number"]],
  ['VdbFile_hGetVoxels', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddVoxels', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_hGetScalarField', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddScalarField', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_hGetVectorField', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddVectorField', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_nFieldCount', "number", ["bigint", "bigint"]],
  ['VdbFile_GetFieldName', null, ["bigint", "bigint", "number", "number"]],
  ['VdbFile_nFieldType', "number", ["bigint", "bigint", "number"]],
  ['ScalarField_hCreate', "bigint", ["bigint"]],
  ['ScalarField_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['ScalarField_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['ScalarField_hBuildFromVoxels', "bigint", ["bigint", "bigint", "number", "number"]],
  ['ScalarField_bIsValid', "boolean", ["bigint", "bigint"]],
  ['ScalarField_Destroy', null, ["bigint", "bigint"]],
  ['ScalarField_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['ScalarField_SetValue', null, ["bigint", "bigint", "number", "number"]],
  ['ScalarField_bGetValue', "boolean", ["bigint", "bigint", "number", "number"]],
  ['ScalarField_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['ScalarField_GetVoxelDimensions', null, ["bigint", "bigint", "number", "number", "number", "number", "number", "number"]],
  ['ScalarField_GetSlice', null, ["bigint", "bigint", "number", "number"]],
  ['ScalarField_TraverseActive', null, ["bigint", "bigint", "number"]],
  ['VectorField_hCreate', "bigint", ["bigint"]],
  ['VectorField_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['VectorField_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['VectorField_hBuildFromVoxels', "bigint", ["bigint", "bigint", "number", "number"]],
  ['VectorField_bIsValid', "boolean", ["bigint", "bigint"]],
  ['VectorField_Destroy', null, ["bigint", "bigint"]],
  ['VectorField_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['VectorField_SetValue', null, ["bigint", "bigint", "number", "number"]],
  ['VectorField_bGetValue', "boolean", ["bigint", "bigint", "number", "number"]],
  ['VectorField_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['VectorField_TraverseActive', null, ["bigint", "bigint", "number"]],
  ['Metadata_hFromVoxels', "bigint", ["bigint", "bigint"]],
  ['Metadata_hFromScalarField', "bigint", ["bigint", "bigint"]],
  ['Metadata_hFromVectorField', "bigint", ["bigint", "bigint"]],
  ['Metadata_Destroy', null, ["bigint", "bigint"]],
  ['Metadata_nCount', "number", ["bigint", "bigint"]],
  ['Metadata_nNameLengthAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_bGetNameAt', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Metadata_nTypeAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_nStringLengthAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_bGetStringAt', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Metadata_bGetFloatAt', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Metadata_bGetVectorAt', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetStringValue', null, ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetFloatValue', null, ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetVectorValue', null, ["bigint", "bigint", "number", "number"]],
  ['MetaData_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['Mesh_GetVertices', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_GetTriangles', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_AddVertices', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_AddTriangles', "number", ["bigint", "bigint", "number", "number"]],
  ['Voxels_RenderImplicitTape', null, ["bigint", "bigint", "number", "number", "number", "number", "number"]],
];

/** Binds every export as a cwrap on an instantiated module. */
export function bindPicoGkRaw(module: PicoGkWasmModule): PicoGkRaw {
  const table: Record<string, unknown> = {};
  for (const [name, returnType, argTypes] of SIGNATURES) {
    table[name] = module.cwrap(name, returnType, argTypes);
  }
  return table as unknown as PicoGkRaw;
}
