// GENERATED by scripts/generate-raw.mjs from src/abi.json — do not edit.
// 140 core exports + 7 own-TU additions (src/pico-bulk.cpp, src/pico-tape.cpp).
// Known upstream header quirks are matched, not fixed: MetaData_RemoveValue (capital
// D), ScalarField_RemoveValue's handle typed PKVECTORFIELD (all handles are uint64_t,
// so it binds by name and works on a scalar field), name-keyed Metadata_*At.
//
// Deliberately glue-free: this module must not import pico.mjs, or the serial
// glue would ride into the picovoxel/multi graph through session.ts. The
// instantiate-and-bind convenience lives in raw.ts (single) beside the entries.

import type { PicoWasmModule } from './types.ts';

/** A PicoGK object handle (uint64_t across the ABI). Never a plain count. */
export type PicoHandle = bigint & { readonly __picoHandle?: never };

export interface PicoRaw {
  Library_GetName(psz: number): void;
  Library_GetVersion(psz: number): void;
  Library_GetBuildInfo(psz: number): void;
  Library_hCreateInstance(fVoxelSizeMM: number): PicoHandle;
  Library_DestroyInstance(hThis: PicoHandle): void;
  Library_nTotalMemUsage(hThis: PicoHandle): bigint;
  Library_nMeshesMemUsage(hThis: PicoHandle): bigint;
  Library_nLatticesMemUsage(hThis: PicoHandle): bigint;
  Library_nPolyLinesMemUsage(hThis: PicoHandle): bigint;
  Library_nVoxelsMemUsage(hThis: PicoHandle): bigint;
  Library_nVdbFilesMemUsage(hThis: PicoHandle): bigint;
  Library_nScalarFieldsMemUsage(hThis: PicoHandle): bigint;
  Library_nVectorFieldsMemUsage(hThis: PicoHandle): bigint;
  Library_nVdbMetasMemUsage(hThis: PicoHandle): bigint;
  Library_nMeshesAllocated(hThis: PicoHandle): bigint;
  Library_nLatticesAllocated(hThis: PicoHandle): bigint;
  Library_nPolyLinesAllocated(hThis: PicoHandle): bigint;
  Library_nVoxelsAllocated(hThis: PicoHandle): bigint;
  Library_nVdbFilesAllocated(hThis: PicoHandle): bigint;
  Library_nScalarFieldsAllocated(hThis: PicoHandle): bigint;
  Library_nVectorFieldsAllocated(hThis: PicoHandle): bigint;
  Library_nVdbMetasAllocated(hThis: PicoHandle): bigint;
  Library_VoxelsToMm(hThis: PicoHandle, pvecVoxelCoordinate: number, pvecMmCoordinate: number): void;
  Library_MmToVoxels(hThis: PicoHandle, pvecMmCoordinate: number, pvecVoxelCoordinate: number): void;
  Mesh_hCreate(hInstance: PicoHandle): PicoHandle;
  Mesh_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  Mesh_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Mesh_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Mesh_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Mesh_nAddVertex(hInstance: PicoHandle, hThis: PicoHandle, pvecVertex: number): number;
  Mesh_nVertexCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Mesh_GetVertex(hInstance: PicoHandle, hThis: PicoHandle, nVertex: number, pvecVertex: number): void;
  Mesh_nAddTriangle(hInstance: PicoHandle, hThis: PicoHandle, psTri: number): number;
  Mesh_nTriangleCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Mesh_GetTriangle(hInstance: PicoHandle, hThis: PicoHandle, nTriangle: number, psTri: number): void;
  Mesh_GetTriangleV(hInstance: PicoHandle, hThis: PicoHandle, nTriangle: number, pvecA: number, pvecB: number, pvecC: number): void;
  Mesh_GetBoundingBox(hInstance: PicoHandle, hThis: PicoHandle, poBox: number): void;
  Lattice_hCreate(hInstance: PicoHandle): PicoHandle;
  Lattice_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Lattice_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Lattice_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Lattice_AddSphere(hInstance: PicoHandle, hThis: PicoHandle, vecCenter: number, fRadius: number): void;
  Lattice_AddBeam(hInstance: PicoHandle, hThis: PicoHandle, pvecA: number, pvecB: number, fRadiusA: number, fRadiusB: number, bRoundCap: boolean): void;
  Voxels_hCreate(hInstance: PicoHandle): PicoHandle;
  Voxels_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  Voxels_hCreateSphere(hInstance: PicoHandle, pvecCenter: number, fRadius: number): PicoHandle;
  Voxels_hCreateCapsule(hInstance: PicoHandle, pvecStart: number, pvecStop: number, fRadius1: number, fRadius2: number): PicoHandle;
  Voxels_hCreateMeshShell(hLib: PicoHandle, hMesh: PicoHandle, fRadius: number): PicoHandle;
  Voxels_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Voxels_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Voxels_bDiagnose(hInstance: PicoHandle, hThis: PicoHandle, psz: number): boolean;
  Voxels_bIsEmpty(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  Voxels_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  Voxels_fVoxelSize(hInstance: PicoHandle, hVoxels: PicoHandle): number;
  Voxels_BoolAdd(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_BoolSubtract(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_BoolIntersect(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): void;
  Voxels_Offset(hInstance: PicoHandle, hThis: PicoHandle, fDist: number): void;
  Voxels_DoubleOffset(hInstance: PicoHandle, hThis: PicoHandle, fDist1: number, fDist2: number): void;
  Voxels_TripleOffset(hInstance: PicoHandle, hThis: PicoHandle, fDist: number): void;
  Voxels_RenderMesh(hInstance: PicoHandle, hThis: PicoHandle, hMesh: PicoHandle): void;
  Voxels_RenderImplicit(hInstance: PicoHandle, hThis: PicoHandle, poBBox: number, pfnSDF: number): void;
  Voxels_IntersectImplicit(hInstance: PicoHandle, hThis: PicoHandle, pfnSDF: number): void;
  Voxels_RenderLattice(hInstance: PicoHandle, hThis: PicoHandle, hLattice: PicoHandle): void;
  Voxels_ProjectZSlice(hInstance: PicoHandle, hThis: PicoHandle, fStartZ: number, fEndZ: number): void;
  Voxels_bIsInside(hInstance: PicoHandle, hThis: PicoHandle, pvecTestPoint: number): boolean;
  Voxels_bIsEqual(hInstance: PicoHandle, hThis: PicoHandle, hOther: PicoHandle): boolean;
  Voxels_fCalculateVolume(hInstance: PicoHandle, hThis: PicoHandle): number;
  Voxels_GetSurfaceNormal(hInstance: PicoHandle, hThis: PicoHandle, pvecSurfacePoint: number, pvecNormal: number): void;
  Voxels_bClosestPointOnSurface(hInstance: PicoHandle, hThis: PicoHandle, pvecSearch: number, pvecSurfacePoint: number): boolean;
  Voxels_bRayCastToSurface(hInstance: PicoHandle, hThis: PicoHandle, pvecSearch: number, pvecDirection: number, pvecSurfacePoint: number): boolean;
  Voxels_GetVoxelDimensions(hInstance: PicoHandle, hThis: PicoHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  Voxels_GetXSlice(hInstance: PicoHandle, hThis: PicoHandle, nXSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetYSlice(hInstance: PicoHandle, hThis: PicoHandle, nYSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetZSlice(hInstance: PicoHandle, hThis: PicoHandle, nZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  Voxels_GetInterpolatedZSlice(hLib: PicoHandle, hThis: PicoHandle, fZSlice: number, pfBuffer: number, pfBackgroundValue: number): void;
  PolyLine_hCreate(hInstance: PicoHandle, pclr: number): PicoHandle;
  PolyLine_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  PolyLine_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  PolyLine_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  PolyLine_nAddVertex(hInstance: PicoHandle, hThis: PicoHandle, pvec: number): number;
  PolyLine_nVertexCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  PolyLine_GetVertex(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number, pvec: number): void;
  PolyLine_GetColor(hInstance: PicoHandle, hThis: PicoHandle, pclr: number): void;
  PolyLine_GetBoundingBox(hLib: PicoHandle, hThis: PicoHandle, poBox: number): void;
  VdbFile_hCreate(hInstance: PicoHandle): PicoHandle;
  VdbFile_hCreateFromFile(hInstance: PicoHandle, pszFileName: number): PicoHandle;
  VdbFile_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  VdbFile_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  VdbFile_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  VdbFile_bSaveToFile(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFileName: number): boolean;
  VdbFile_hGetVoxels(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddVoxels(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hVoxels: PicoHandle): number;
  VdbFile_hGetScalarField(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddScalarField(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hScalarField: PicoHandle): number;
  VdbFile_hGetVectorField(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): PicoHandle;
  VdbFile_nAddVectorField(hInstance: PicoHandle, hVdbFile: PicoHandle, pszFieldName: number, hVectorField: PicoHandle): number;
  VdbFile_nFieldCount(hInstance: PicoHandle, hVdbFile: PicoHandle): number;
  VdbFile_GetFieldName(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number, psz: number): void;
  VdbFile_nFieldType(hInstance: PicoHandle, hVdbFile: PicoHandle, nIndex: number): number;
  ScalarField_hCreate(hInstance: PicoHandle): PicoHandle;
  ScalarField_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  ScalarField_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  ScalarField_hBuildFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle, fScalarValue: number, fSdThreshold: number): PicoHandle;
  ScalarField_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  ScalarField_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  ScalarField_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  ScalarField_SetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, fValue: number): void;
  ScalarField_bGetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pfValue: number): boolean;
  ScalarField_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number): void;
  ScalarField_GetVoxelDimensions(hInstance: PicoHandle, hThis: PicoHandle, pnXOrigin: number, pnYOrigin: number, pnZOrigin: number, pnXSize: number, pnYSize: number, pnZSize: number): void;
  ScalarField_GetSlice(hInstance: PicoHandle, hThis: PicoHandle, nZSlice: number, pfBuffer: number): void;
  ScalarField_TraverseActive(hInstance: PicoHandle, hThis: PicoHandle, pfnCallback: number): void;
  VectorField_hCreate(hInstance: PicoHandle): PicoHandle;
  VectorField_hCreateCopy(hInstance: PicoHandle, hSource: PicoHandle): PicoHandle;
  VectorField_hCreateFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  VectorField_hBuildFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle, vecValue: number, fSdThreshold: number): PicoHandle;
  VectorField_bIsValid(hInstance: PicoHandle, hThis: PicoHandle): boolean;
  VectorField_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  VectorField_nMemUsage(hInstance: PicoHandle, hThis: PicoHandle): bigint;
  VectorField_SetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pvecValue: number): void;
  VectorField_bGetValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number, pvecValue: number): boolean;
  VectorField_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pvecPosition: number): void;
  VectorField_TraverseActive(hInstance: PicoHandle, hThis: PicoHandle, pfnCallback: number): void;
  Metadata_hFromVoxels(hInstance: PicoHandle, hVoxels: PicoHandle): PicoHandle;
  Metadata_hFromScalarField(hInstance: PicoHandle, hScalarField: PicoHandle): PicoHandle;
  Metadata_hFromVectorField(hInstance: PicoHandle, hVectorField: PicoHandle): PicoHandle;
  Metadata_Destroy(hInstance: PicoHandle, hThis: PicoHandle): void;
  Metadata_nCount(hInstance: PicoHandle, hThis: PicoHandle): number;
  Metadata_nNameLengthAt(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number): number;
  Metadata_bGetNameAt(hInstance: PicoHandle, hThis: PicoHandle, nIndex: number, psz: number, nMaxStringLen: number): boolean;
  Metadata_nTypeAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number): number;
  Metadata_nStringLengthAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number): number;
  Metadata_bGetStringAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pszValue: number, nMaxStringLen: number): boolean;
  Metadata_bGetFloatAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pfValue: number): boolean;
  Metadata_bGetVectorAt(hInstance: PicoHandle, hThis: PicoHandle, psz: number, pvecValue: number): boolean;
  Metadata_SetStringValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, pszValue: number): void;
  Metadata_SetFloatValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, fValue: number): void;
  Metadata_SetVectorValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number, pvecValue: number): void;
  MetaData_RemoveValue(hInstance: PicoHandle, hThis: PicoHandle, pszFieldName: number): void;
  Mesh_GetVertices(hLib: PicoHandle, hThis: PicoHandle, pvecBuffer: number, nBufferCount: number): number;
  Mesh_GetTriangles(hLib: PicoHandle, hThis: PicoHandle, psBuffer: number, nBufferCount: number): number;
  Mesh_AddVertices(hLib: PicoHandle, hThis: PicoHandle, pvecBuffer: number, nCount: number): number;
  Mesh_AddTriangles(hLib: PicoHandle, hThis: PicoHandle, psBuffer: number, nCount: number): number;
  Voxels_RenderImplicitTape(hLib: PicoHandle, hThis: PicoHandle, poBBox: number, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
  Voxels_RenderImplicitTapeCompose(hLib: PicoHandle, hThis: PicoHandle, poBBox: number, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
  Voxels_IntersectImplicitTape(hLib: PicoHandle, hThis: PicoHandle, pnInstructions: number, nInstructionCount: number, pfConstants: number, nConstantCount: number): void;
}

const SIGNATURES: ReadonlyArray<readonly [string, string | null, readonly string[]]> = [
  ['Library_GetName', null, ["number"]],
  ['Library_GetVersion', null, ["number"]],
  ['Library_GetBuildInfo', null, ["number"]],
  ['Library_hCreateInstance', "bigint", ["number"]],
  ['Library_DestroyInstance', null, ["bigint"]],
  ['Library_nTotalMemUsage', "bigint", ["bigint"]],
  ['Library_nMeshesMemUsage', "bigint", ["bigint"]],
  ['Library_nLatticesMemUsage', "bigint", ["bigint"]],
  ['Library_nPolyLinesMemUsage', "bigint", ["bigint"]],
  ['Library_nVoxelsMemUsage', "bigint", ["bigint"]],
  ['Library_nVdbFilesMemUsage', "bigint", ["bigint"]],
  ['Library_nScalarFieldsMemUsage', "bigint", ["bigint"]],
  ['Library_nVectorFieldsMemUsage', "bigint", ["bigint"]],
  ['Library_nVdbMetasMemUsage', "bigint", ["bigint"]],
  ['Library_nMeshesAllocated', "bigint", ["bigint"]],
  ['Library_nLatticesAllocated', "bigint", ["bigint"]],
  ['Library_nPolyLinesAllocated', "bigint", ["bigint"]],
  ['Library_nVoxelsAllocated', "bigint", ["bigint"]],
  ['Library_nVdbFilesAllocated', "bigint", ["bigint"]],
  ['Library_nScalarFieldsAllocated', "bigint", ["bigint"]],
  ['Library_nVectorFieldsAllocated', "bigint", ["bigint"]],
  ['Library_nVdbMetasAllocated', "bigint", ["bigint"]],
  ['Library_VoxelsToMm', null, ["bigint", "number", "number"]],
  ['Library_MmToVoxels', null, ["bigint", "number", "number"]],
  ['Mesh_hCreate', "bigint", ["bigint"]],
  ['Mesh_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['Mesh_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Mesh_Destroy', null, ["bigint", "bigint"]],
  ['Mesh_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Mesh_nAddVertex', "number", ["bigint", "bigint", "number"]],
  ['Mesh_nVertexCount', "number", ["bigint", "bigint"]],
  ['Mesh_GetVertex', null, ["bigint", "bigint", "number", "number"]],
  ['Mesh_nAddTriangle', "number", ["bigint", "bigint", "number"]],
  ['Mesh_nTriangleCount', "number", ["bigint", "bigint"]],
  ['Mesh_GetTriangle', null, ["bigint", "bigint", "number", "number"]],
  ['Mesh_GetTriangleV', null, ["bigint", "bigint", "number", "number", "number", "number"]],
  ['Mesh_GetBoundingBox', null, ["bigint", "bigint", "number"]],
  ['Lattice_hCreate', "bigint", ["bigint"]],
  ['Lattice_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Lattice_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Lattice_Destroy', null, ["bigint", "bigint"]],
  ['Lattice_AddSphere', null, ["bigint", "bigint", "number", "number"]],
  ['Lattice_AddBeam', null, ["bigint", "bigint", "number", "number", "number", "number", "boolean"]],
  ['Voxels_hCreate', "bigint", ["bigint"]],
  ['Voxels_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['Voxels_hCreateSphere', "bigint", ["bigint", "number", "number"]],
  ['Voxels_hCreateCapsule', "bigint", ["bigint", "number", "number", "number", "number"]],
  ['Voxels_hCreateMeshShell', "bigint", ["bigint", "bigint", "number"]],
  ['Voxels_bIsValid', "boolean", ["bigint", "bigint"]],
  ['Voxels_Destroy', null, ["bigint", "bigint"]],
  ['Voxels_bDiagnose', "boolean", ["bigint", "bigint", "number"]],
  ['Voxels_bIsEmpty', "boolean", ["bigint", "bigint"]],
  ['Voxels_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['Voxels_fVoxelSize', "number", ["bigint", "bigint"]],
  ['Voxels_BoolAdd', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_BoolSubtract', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_BoolIntersect', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_Offset', null, ["bigint", "bigint", "number"]],
  ['Voxels_DoubleOffset', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_TripleOffset', null, ["bigint", "bigint", "number"]],
  ['Voxels_RenderMesh', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_RenderImplicit', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_IntersectImplicit', null, ["bigint", "bigint", "number"]],
  ['Voxels_RenderLattice', null, ["bigint", "bigint", "bigint"]],
  ['Voxels_ProjectZSlice', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_bIsInside', "boolean", ["bigint", "bigint", "number"]],
  ['Voxels_bIsEqual', "boolean", ["bigint", "bigint", "bigint"]],
  ['Voxels_fCalculateVolume', "number", ["bigint", "bigint"]],
  ['Voxels_GetSurfaceNormal', null, ["bigint", "bigint", "number", "number"]],
  ['Voxels_bClosestPointOnSurface', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Voxels_bRayCastToSurface', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetVoxelDimensions', null, ["bigint", "bigint", "number", "number", "number", "number", "number", "number"]],
  ['Voxels_GetXSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetYSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetZSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['Voxels_GetInterpolatedZSlice', null, ["bigint", "bigint", "number", "number", "number"]],
  ['PolyLine_hCreate', "bigint", ["bigint", "number"]],
  ['PolyLine_bIsValid', "boolean", ["bigint", "bigint"]],
  ['PolyLine_Destroy', null, ["bigint", "bigint"]],
  ['PolyLine_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['PolyLine_nAddVertex', "number", ["bigint", "bigint", "number"]],
  ['PolyLine_nVertexCount', "number", ["bigint", "bigint"]],
  ['PolyLine_GetVertex', null, ["bigint", "bigint", "number", "number"]],
  ['PolyLine_GetColor', null, ["bigint", "bigint", "number"]],
  ['PolyLine_GetBoundingBox', null, ["bigint", "bigint", "number"]],
  ['VdbFile_hCreate', "bigint", ["bigint"]],
  ['VdbFile_hCreateFromFile', "bigint", ["bigint", "number"]],
  ['VdbFile_bIsValid', "boolean", ["bigint", "bigint"]],
  ['VdbFile_Destroy', null, ["bigint", "bigint"]],
  ['VdbFile_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['VdbFile_bSaveToFile', "boolean", ["bigint", "bigint", "number"]],
  ['VdbFile_hGetVoxels', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddVoxels', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_hGetScalarField', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddScalarField', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_hGetVectorField', "bigint", ["bigint", "bigint", "number"]],
  ['VdbFile_nAddVectorField', "number", ["bigint", "bigint", "number", "bigint"]],
  ['VdbFile_nFieldCount', "number", ["bigint", "bigint"]],
  ['VdbFile_GetFieldName', null, ["bigint", "bigint", "number", "number"]],
  ['VdbFile_nFieldType', "number", ["bigint", "bigint", "number"]],
  ['ScalarField_hCreate', "bigint", ["bigint"]],
  ['ScalarField_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['ScalarField_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['ScalarField_hBuildFromVoxels', "bigint", ["bigint", "bigint", "number", "number"]],
  ['ScalarField_bIsValid', "boolean", ["bigint", "bigint"]],
  ['ScalarField_Destroy', null, ["bigint", "bigint"]],
  ['ScalarField_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['ScalarField_SetValue', null, ["bigint", "bigint", "number", "number"]],
  ['ScalarField_bGetValue', "boolean", ["bigint", "bigint", "number", "number"]],
  ['ScalarField_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['ScalarField_GetVoxelDimensions', null, ["bigint", "bigint", "number", "number", "number", "number", "number", "number"]],
  ['ScalarField_GetSlice', null, ["bigint", "bigint", "number", "number"]],
  ['ScalarField_TraverseActive', null, ["bigint", "bigint", "number"]],
  ['VectorField_hCreate', "bigint", ["bigint"]],
  ['VectorField_hCreateCopy', "bigint", ["bigint", "bigint"]],
  ['VectorField_hCreateFromVoxels', "bigint", ["bigint", "bigint"]],
  ['VectorField_hBuildFromVoxels', "bigint", ["bigint", "bigint", "number", "number"]],
  ['VectorField_bIsValid', "boolean", ["bigint", "bigint"]],
  ['VectorField_Destroy', null, ["bigint", "bigint"]],
  ['VectorField_nMemUsage', "bigint", ["bigint", "bigint"]],
  ['VectorField_SetValue', null, ["bigint", "bigint", "number", "number"]],
  ['VectorField_bGetValue', "boolean", ["bigint", "bigint", "number", "number"]],
  ['VectorField_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['VectorField_TraverseActive', null, ["bigint", "bigint", "number"]],
  ['Metadata_hFromVoxels', "bigint", ["bigint", "bigint"]],
  ['Metadata_hFromScalarField', "bigint", ["bigint", "bigint"]],
  ['Metadata_hFromVectorField', "bigint", ["bigint", "bigint"]],
  ['Metadata_Destroy', null, ["bigint", "bigint"]],
  ['Metadata_nCount', "number", ["bigint", "bigint"]],
  ['Metadata_nNameLengthAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_bGetNameAt', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Metadata_nTypeAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_nStringLengthAt', "number", ["bigint", "bigint", "number"]],
  ['Metadata_bGetStringAt', "boolean", ["bigint", "bigint", "number", "number", "number"]],
  ['Metadata_bGetFloatAt', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Metadata_bGetVectorAt', "boolean", ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetStringValue', null, ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetFloatValue', null, ["bigint", "bigint", "number", "number"]],
  ['Metadata_SetVectorValue', null, ["bigint", "bigint", "number", "number"]],
  ['MetaData_RemoveValue', null, ["bigint", "bigint", "number"]],
  ['Mesh_GetVertices', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_GetTriangles', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_AddVertices', "number", ["bigint", "bigint", "number", "number"]],
  ['Mesh_AddTriangles', "number", ["bigint", "bigint", "number", "number"]],
  ['Voxels_RenderImplicitTape', null, ["bigint", "bigint", "number", "number", "number", "number", "number"]],
  ['Voxels_RenderImplicitTapeCompose', null, ["bigint", "bigint", "number", "number", "number", "number", "number"]],
  ['Voxels_IntersectImplicitTape', null, ["bigint", "bigint", "number", "number", "number", "number"]],
];

/** Binds every export as a cwrap on an instantiated module. */
export function bindPicoRaw(module: PicoWasmModule): PicoRaw {
  const table: Record<string, unknown> = {};
  for (const [name, returnType, argTypes] of SIGNATURES) {
    table[name] = module.cwrap(name, returnType, argTypes);
  }
  return table as unknown as PicoRaw;
}
